HotelBookingAdmin/Controllers/OrderController.cs
using HotelBookingAdmin.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelBookingAdmin.Models;

namespace HotelBookingAdmin.Controllers
{
  public class OrderController : Controller
  {
    // GET: Order
    public ActionResult Index()
    {
      ViewBag.HoaDons = DBOrder.getHoaDons();
      ViewBag.KhachHangs = DBCustomer.getCustomers();
      ViewBag.NhanViens = DBEmployee.getEmployees();
      ViewBag.PhongTrongs = DBRoom.getPhongs().Where(item => item.tinhTrang == "empty").ToList();
      ViewBag.DichVus = DBServices.getServices();

      return View();
    }

    [HttpPost]
    public JsonResult UpdateOrder(HoaDon hd, string[] services)
    {
      DBServices.removeServicesDetail(hd);
      DBServices.createServicesDetail(hd, services);
      HoaDon kq = DBOrder.updateHoaDon(hd);
      HoaDon updatedHD = DBOrder.getHoaDon(kq);

      return Json(new { result = updatedHD, listHD = DBOrder.getHoaDons().Where(item => item.tinhTrang == false).ToList(), phongTrongs = DBRoom.getPhongs().Where(item => item.tinhTrang == "empty").ToList() });
    }

    [HttpPost]
    public JsonResult DeleteOrder(int maHD)
    {
      DBOrder.deleteOrder(maHD);
      return Json(new { listHD = DBOrder.getHoaDons(), phongTrongs = DBRoom.getPhongs().Where(item => item.tinhTrang == "empty").ToList() });
    }

    [HttpPost]
    public JsonResult CreateOrder(HoaDon newHD, string[] services)
    {
      newHD.tinhTrang = false;
      newHD.maNV = ((NhanVien)Session["NhanVien"]).MaNV;

      HoaDon kq = DBOrder.createHoaDon(newHD);
      DBServices.createServicesDetail(newHD, services);
      HoaDon hd = DBOrder.updateHoaDon(kq);

      return Json(new { result = hd, listHD =  DBOrder.getHoaDons().Where(item => item.tinhTrang == false).ToList(), phongTrongs = DBRoom.getPhongs().Where(item => item.tinhTrang == "empty").ToList() });
    }

    [HttpPost]
    public JsonResult GetServicesDetail(int maHD)
    {
      List<ChiTietDichVu> services = DBServices.getServiceDetailByOrder(maHD);
      return Json(new { services });
    }
  }
}

HotelBookingAdmin/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelBookingAdmin.Helpers;
using HotelBookingAdmin.Models;

namespace HotelBookingAdmin.Controllers
{
  public class RoomController : Controller
  {
    // GET: Room
    public ActionResult Index()
    {
      ViewBag.StatisticsInfo = DBHelper.getStatistics();
      ViewBag.TotalRoom = DBHelper.countTotalRoom();
      ViewBag.Phongs = DBRoom.getPhongs();
      ViewBag.RatePercents = DBHelper.getRatePercent();

      return View();
    }

    [HttpGet]
    public JsonResult GetPhong()
    {
      List<Phong> phongs = DBRoom.getPhongs();
      return Json(new { listPhong = phongs }, JsonRequestBehavior.AllowGet);
    }

    [HttpPost]
    public JsonResult UpdateRoom(Phong updatePhong)
    {
      List<Phong> listPhong = DBRoom.updateRoom(updatePhong);
      HoaDon hd = DBOrder.getHoaDons().FirstOrDefault(item => item.maPhong == updatePhong.maPhong);
      
      if (hd != null)
      {
        DBOrder.updateHoaDon(hd);
      }

      return Json(new { phongs = listPhong });
    }
  }
}

HotelBookingAdmin/Views/Shared/PartialLayout/_AddCustomer.cshtml
@{
  ViewBag.Title = "_AddEmployee";
}

<div class="modal fade" id="modal-add" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Customer Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="#" method="post" id="create-customer-form">
          <div class="form-group row">
            <label for="modal-add-email-text" class="col-sm-3 col-form-label">Email</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-add-email-text" placeholder="Email" required />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-name-text" class="col-sm-3 col-form-label">Fullname</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-add-name-text" placeholder="Fullname" required />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-gender-text" class="col-sm-3 col-form-label">Gender (Female/Male)</label>
            <div class="col-sm-1">
              <input type="checkbox" value="Female" class="form-control" id="modal-add-gender-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-dob-text" class="col-sm-3 col-form-label">DOB</label>
            <div class="col-sm-9">
              <input type="date" class="form-control" id="modal-add-dob-text" value="2000-1-12" min="@DateTime.Now.AddYears(-100).ToString("yyyy-MM-dd")" max="@DateTime.Now.AddYears(-18).ToString("yyyy-MM-dd")" required />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-address-text" class="col-sm-3 col-form-label">Address</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-add-address-text" placeholder="Address" required />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-phone-text" class="col-sm-3 col-form-label">Phone number</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-add-phone-text" placeholder="Phone number" maxlength="10" required />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-password-text" class="col-sm-3 col-form-label">Password</label>
            <div class="col-sm-9">
              <input type="password" class="form-control" id="modal-add-password-text" placeholder="Password" required />
            </div>
          </div>

          <div class="modal-footer justify-content-center">
            <button type="submit" class="btn btn-info" id="add-submit-btn">Submit</button>
          </div>
        </form>
      </div>
      
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

HotelBookingAdmin/Views/Shared/PartialLayout/_AddOrder.cshtml
@using HotelBookingAdmin.Models
@{
  List<KhachHang> khachHangs = (List<KhachHang>)ViewData["khachHangs"];
  List<Phong> phongTrongs = (List<Phong>)ViewData["phongTrongs"];
  List<NhanVien> nhanViens = (List<NhanVien>)ViewData["nhanViens"];
  List<DichVu> dichVus = (List<DichVu>)ViewData["dichVus"];
}

<div class="modal fade" id="modal-add" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Order Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">

        <img class="img-fluid d-block m-auto" id="modal-img" src="https://taker.io/wp-content/uploads/2019/10/Online-Ordering-System-for-Restaurants-min.png" style="width: 200px;" />

        <form action="" method="post" class="mt-3" id="create-order-form">
          <div class="form-group row">
            <label for="modal-add-email-text" class="col-sm-4 col-form-label">Email</label>
            <div class="col-sm-8">
              <select id="modal-add-email-text" class="form-control" required>
                @foreach (KhachHang kh in khachHangs)
                {
                  <option value="@kh.email">@kh.email</option>
                }
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-name-text" class="col-sm-4 col-form-label">Room name</label>
            <div class="col-sm-8">
              <select id="modal-add-name-text" class="form-control" required>
                @foreach (Phong phong in phongTrongs)
                {
                  <option value="@phong.tenPhong">@phong.tenPhong</option>
                }
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-name-text" class="col-sm-4 col-form-label">Service name</label>
            <div class="col-sm-8" id="add-services-checkbox-container">
              @foreach (DichVu dv in dichVus)
              {
                <div class="ml-4">
                  <input class="form-check-input add-checkbox" type="checkbox" value="@dv.maDichVu" id="add-service-@dv.maDichVu" name="@dv.maDichVu">
                  <label class="form-check-label" for="add-service-@dv.maDichVu">
                    @dv.tenDichVu
                  </label>
                </div>
              }
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-booking-date-text" class="col-sm-4 col-form-label">Booking date</label>
            <div class="col-sm-8">
              <input type="date" class="form-control" id="modal-add-booking-date-text"  value="@DateTime.Now.ToString("yyyy-MM-dd")" min="@DateTime.Now.ToString("yyyy-MM-dd")" required />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-add-checkout-date-text" class="col-sm-4 col-form-label">Check-out date</label>
            <div class="col-sm-8">
              <input type="date" class="form-control" value="@DateTime.Now.AddDays(1).ToString("yyyy-MM-dd")" min="@DateTime.Now.AddDays(1).ToString("yyyy-MM-dd")" id="modal-add-checkout-date-text" required />
            </div>
          </div>

          <div class="modal-footer justify-content-center">
            <button type="submit" class="btn btn-success" id="add-submit-btn">Submit</button>
          </div>
        </form>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

HotelBookingAdmin/Views/Shared/PartialLayout/_EditEmployee.cshtml
@{
  ViewBag.Title = "_EditEmployee";
}


<div class="modal fade" id="modal-edit" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Employee Edit Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post">
          <div class="form-group row">
            <label for="modal-edit-name-text" class="col-sm-3 col-form-label">Fullname</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-name-text" />
            </div>
          </div>

          @*<div class="form-group row">
            <label for="modal-edit-role-text" class="col-sm-3 col-form-label">Role</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-role-text" />
            </div>
          </div>*@

          <div class="form-group row">
            <label for="modal-edit-role-text" class="col-sm-3 col-form-label">Role</label>
            <div class="col-sm-9">
              <select id="modal-edit-role-text" class="form-control">
                <option value="admin">Admin</option>
                <option value="employee">Employee</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-edit-gender-text" class="col-sm-3 col-form-label">Gender (Female/Male)</label>
            <div class="col-sm-1">
              <input type="checkbox" value="Female" class="form-control" id="modal-edit-gender-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-edit-dob-text" class="col-sm-3 col-form-label">DOB</label>
            <div class="col-sm-9">
              <input type="date" class="form-control" id="modal-edit-dob-text" value="2000-1-12" min="@DateTime.Now.AddYears(-25).ToString("yyyy-MM-dd")" max="@DateTime.Now.AddYears(-18).ToString("yyyy-MM-dd")" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-edit-email-text" class="col-sm-3 col-form-label">Email</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-email-text" readonly/>
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-edit-phone-text" class="col-sm-3 col-form-label">Phone number</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-phone-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-edit-address-text" class="col-sm-3 col-form-label">Address</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-address-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-edit-password-text" class="col-sm-3 col-form-label">Password</label>
            <div class="col-sm-9">
              <input type="password" class="form-control" id="modal-edit-password-text" placeholder="password" />
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-info" data-dismiss="modal" id="edit-submit-btn">Submit</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

HotelBookingAdmin/Views/Shared/PartialLayout/_EditRoom.cshtml
<div class="modal fade" id="modal-edit" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Room Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">

        <img class="img-fluid" id="modal-edit-img" src="https://media-cdn.tripadvisor.com/media/photo-s/13/d8/ea/1b/a-room-at-the-beach.jpg" alt="Image thumbnail"/>

        <form action="" method="post" class="mt-3">
          <div class="form-group row">
            <label for="modal-code-text" class="col-sm-3 col-form-label">No.</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-code-text" disabled />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-name-text" class="col-sm-3 col-form-label">Room name</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="modal-edit-name-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-status-text" class="col-sm-3 col-form-label">Status</label>
            <div class="col-sm-9">
              <input type="text" id="modal-edit-status-text" class="form-control" disabled />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-type-text" class="col-sm-3 col-form-label">Room type</label>
            <div class="col-sm-9">
              <select id="modal-edit-type-text" class="form-control">
                <option value="lp01">LP01</option>
                <option value="lp02">LP02</option>
                <option value="lp03">LP03</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-price-text" class="col-sm-3 col-form-label">Price($)</label>
            <div class="col-sm-9">
              <input type="number" class="form-control" id="modal-edit-price-text" min="10" max="300" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-discount-text" class="col-sm-3 col-form-label">Discount($)</label>
            <div class="col-sm-9">
              <select id="modal-edit-discount-text" class="form-control">
                <option value="0">0%</option>
                <option value="0.1">10%</option>
                <option value="0.2">20%</option>
                <option value="0.3">30%</option>
              </select>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-success" data-dismiss="modal" id="modal-edit-submit">Submit</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

HotelBookingAdmin/Views/Shared/PartialLayout/_Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong><a href="https://adminlte.io">TREE HOTEL</a></strong>
</footer>

HotelBookingAdmin/Views/Shared/PartialLayout/_MainNavigation.cshtml
@using HotelBookingAdmin.Helpers
@using HotelBookingAdmin.Models
@{
  NhanVien nv = (NhanVien)Session["NhanVien"];
}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <a href="@Url.Action("Index", "Home")" class="brand-link">
    <img src="~/Assets/img/logo.png" alt="Tree Hotel Logo" class="img-fluid"
         style="opacity: .8; width: 150px;">
    <span class="brand-text font-weight-light"></span>
  </a>
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="~/Assets/img/user10.png" class="img-circle elevation-2" alt="User Image" width="160">
      </div>
      <div class="info">
        <a href="@Url.Action("Profile", "Customer")" class="d-block status-name">@nv.TenNV</a>
      </div>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item ">
          <a href="@Url.Action("Index", "Home")" class="nav-link @Html.IsSelected("Home", "Index", "active")">
            <i class="nav-icon fas fa-home"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        <li class="nav-item ">
          <a href="@Url.Action("Employee", "Customer")" class="nav-link @Html.IsSelected("Customer", "Employee", "active")">
            <i class="nav-icon fas fa-users"></i>
            <p>
              Employee
            </p>
          </a>
        </li>
        <li class="nav-item ">
          <a href="@Url.Action("Customer", "Customer")" class="nav-link @Html.IsSelected("Customer", "Customer", "active")">
            <i class="nav-icon fas fa-user-lock"></i>
            <p>
              Customer
            </p>
          </a>
        </li>

        <li class="nav-item ">
          <a href="@Url.Action("Index", "Room")" class="nav-link @Html.IsSelected("Room", "Index", "active")">
            <i class="nav-icon fas fa-hotel"></i>
            <p>
              Room
            </p>
          </a>
        </li>
        <li class="nav-item ">
          <a href="@Url.Action("Index", "Order")" class="nav-link @Html.IsSelected("Order", "Index", "active")">
            <i class="nav-icon fas fa-money-check"></i>
            <p>
              Order
            </p>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</aside>

HotelBookingAdmin/Views/Shared/PartialLayout/_PageHeader.cshtml
@model string

<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">@Model</h1>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /.content-header -->

HotelBookingAdmin/Views/Shared/PartialLayout/_Scripts.cshtml
<script src="~/Assets/plugins/jquery/jquery.min.js"></script>
<script src="~/Assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<script src="~/Assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Assets/plugins/chart.js/Chart.min.js"></script>
<script src="~/Assets/plugins/sparklines/sparkline.js"></script>
<script src="~/Assets/plugins/jquery-knob/jquery.knob.min.js"></script>
<script src="~/Assets/plugins/moment/moment.min.js"></script>
<script src="~/Assets/plugins/daterangepicker/daterangepicker.js"></script>
<script src="~/Assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="~/Assets/js/adminlte.min.js"></script>

HotelBookingAdmin/Views/Shared/PartialLayout/_ServicesInfo.cshtml
@using HotelBookingAdmin.Models
@{
  List<DichVu> dichVus = (List<DichVu>)ViewData["dichVus"];
}

<div class="modal fade" id="modal-services" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Services Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">

        <img class="img-fluid d-block m-auto" id="modal-img" src="https://codecungtrung.com/wp-content/uploads/2019/12/pr.png" style="width: 200px;" />

        <form action="" method="post" class="mt-3" id="create-order-form">
          @foreach (DichVu dv in dichVus)
          {
            <div class="form-group m-auto d-flex w-50 justify-content-between">
              <label for="modal-add-email-text" class="col-form-label w-50 text-right">@dv.tenDichVu</label>
              <div class="text-end w-25 col-form-label">
                $@string.Format("{0:#.00}", dv.giaTien)
              </div>
            </div>
          }
        </form>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

HotelBookingAdmin/Views/Shared/PartialLayout/_Styles.cshtml
<link rel="stylesheet" href="~/Assets/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="~/Assets/css/adminlte.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<link rel="stylesheet"
      href="~/Assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" />
<link rel="stylesheet" href="~/Assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
<link rel="stylesheet" href="~/Assets/plugins/fullcalendar/main.css">
<link rel="stylesheet" href="~/Assets/plugins/daterangepicker/daterangepicker.css" />
<!-- DataTables -->
<link rel="stylesheet" href="~/Assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/Assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/Assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

<link rel="stylesheet" href="~/Assets/plugins/toastr/toastr.min.css">

HotelBookingAdmin/Views/Shared/PartialLayout/_TopNavigation.cshtml
@using HotelBookingAdmin.Models
@{
  NhanVien nv = (NhanVien)Session["NhanVien"];
}


<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="@Url.Action("Index", "Home")" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="@Url.Action("Contact", "Home")" class="nav-link">Contact</a>
    </li>

    @if (nv != null)
    {
      <li class="nav-item d-none d-sm-inline-block">
        <a href="@Url.Action("Logout", "Customer")" class="nav-link">Logout</a>
      </li>
    }
    else
    {
      <li class="nav-item d-none d-sm-inline-block">
        <a href="@Url.Action("Index", "Customer")" class="nav-link">Login</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="@Url.Action("Register", "Customer")" class="nav-link">Register</a>
      </li>
    }
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
  </ul>
</nav>

HotelBookingAdmin/Views/Shared/PartialLayout/_ViewEmployee.cshtml
@{
  ViewBag.Title = "_ViewEmployee";
}

<div class="modal fade" id="modal-default" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Employee Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post">
          <div class="form-group row">
            <label for="modal-name-text" class="col-sm-3 col-form-label">Fullname</label>
            <div class="col-sm-9">
              <input type="text" readonly class="form-control" id="modal-name-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-role-text" class="col-sm-3 col-form-label">Role</label>
            <div class="col-sm-9">
              <input type="text" readonly class="form-control" id="modal-role-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-gender-text" class="col-sm-3 col-form-label">Gender (Female/Male)</label>
            <div class="col-sm-1">
              <input type="checkbox" value="Female" disabled class="form-control" id="modal-gender-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-dob-text" class="col-sm-3 col-form-label">DOB</label>
            <div class="col-sm-9">
              <input type="date" class="form-control" id="modal-dob-text" value="2000/1/12" disabled/>
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-email-text" class="col-sm-3 col-form-label">Email</label>
            <div class="col-sm-9">
              <input type="text" readonly class="form-control" id="modal-email-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-phone-text" class="col-sm-3 col-form-label">Phone number</label>
            <div class="col-sm-9">
              <input type="text" readonly class="form-control" id="modal-phone-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-address-text" class="col-sm-3 col-form-label">Address</label>
            <div class="col-sm-9">
              <input type="text" readonly class="form-control" id="modal-address-text" />
            </div>
          </div>

          <div class="form-group row">
            <label for="modal-password-text" class="col-sm-3 col-form-label">Password</label>
            <div class="col-sm-9">
              <input type="password" readonly class="form-control" id="modal-password-text" />
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-success" data-dismiss="modal">Done</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>